version: 2
jobs:
  test:
    working_directory: /workdir
    docker:
      - image: golang:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./bin/test.sh
            ./bin/coverage.sh
            bash <(curl -s https://codecov.io/bash)

  release:
    working_directory: /workdir
    docker:
      - image: golang:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            go get -u github.com/mitchellh/gox
            ./bin/build.sh
            mkdir -p /tmp/artifacts
            mv ./build/myip_* /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: release
